{% set version = "2.6.0" %}

package:
  name: tensorflow
  version: {{ version }}

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [not linux]

requirements:
  host:
    - tensorflow-base {{ version }}
  run:
    - {{ pin_compatible("tensorflow-base", max_pin="x.x.x") }}  

test:
  commands:
    - saved_model_cli --help

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - izahn
