{% set version = "2.6.0" %}

package:
  name: tensorflow-base
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 41b32eeaddcbc02b0583660bcf508469550e4cd0f86b22d2abe72dfebeacde0f
  patches:
    - 0103-BUILD-changes-for-external-sqlite-package.patch
    - 0101-include-c-and-cc-headers.patch
    - 0107-do-not-hardcode-ca-cert-location.patch
    - 0201-add-additional-cuda-rpaths.patch

build:
  number: 0
  string:  cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  skip: True  # [not x86_64]
  skip: True  # [not linux]
  skip: True  # [cuda_compiler_version == "None"]
  entry_points:
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    # The tensorboard package adds this entry point.
    # - tensorboard = tensorboard.main:run_main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - git
    - wheel
    - setuptools
    - pip
    - bazel
    - nasm
    - sed
    - coreutils
    - binutils
    - clang
    - clangdev
  host:
    # GPU requirements
    - cudnn
    - nccl
    # conda build requirements
    - python
    - pip
    - zlib
    - libpng
    - libcurl
    - unzip
    - zip
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS
    - astor >=0.7.1
    - cython >=0.28.4
    - dill >=0.3.1.1
    - giflib
    - grpc-cpp
    - flatbuffers
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.10.0
    - astunparse >=1.6.3
    - google-pasta >=0.2
    - h5py >=2.10
    - keras-preprocessing >=1.1.2
    - numpy 1.19.*
    - opt_einsum
    - protobuf >=3.9.2
    - six >=1.15.0
    - termcolor >=1.1.0
    - typing_extensions >=3.7.4
    - wheel >=0.35
    - wrapt >=1.11.1
    - gast
    - tensorboard >=2.6.0,<2.7
    - tensorflow-estimator >=2.6.0,<2.7

test:
  imports:
    - tensorflow
  files:
    - gpu_test.py
  commands:
    # - freeze_graph --help
    - saved_model_cli --help
    - tflite_convert --help
    - toco_from_protos --help
    - toco --help

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - farhantejani
    - ghego
    - gilbertfrancois
    - h-vetinari
    - hajapy
    - jschueller
    - njzjz
    - waitingkuo
    - xhochy
